apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp
    env: prod
spec:
  selector:
    matchLabels:
      env: prod
  replicas: 4
  template:
    metadata:
      name: nginx
      labels:
        env: prod
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
